# Generated by Django 5.0.1 on 2024-01-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_postcommentrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentrating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.post'),
        ),
    ]
