# Generated by Django 5.0.1 on 2024-01-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_postcommentrating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
